#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
expectedValue=4
ARGC=("$#")
ARGV=("$@")

if [ $ARGC -eq $expectedValue ]
then
	scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3@$2":~
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	echo "$ARGC"
fi;