#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart