#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
