#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '42 a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start