#!/usr/bin/env bash
#Requirements:
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#	The name of the custom HTTP header must be X-Served-By
#	The value of the custom HTTP header must be the hostname of the server Nginx is running on
#Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.html

# Create un link of redirection for the path /redirect_me
sudo sed -i '42 a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Custom page 404
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '43 a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

#add header
sudo sed -i '18i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restar