#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100 fizzbuzz.
i=1
while [ $i -lt 101 ]
do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	let i=i+1
done