#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times,
#but for the 9th iteration, displays Holberton School
#and then Hi on a new line.
count=0
while [ $count -lt 10 ]
do
	echo "Holberton School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	let count=count+1
done