#!/usr/bin/env bash
# Bash script what login with nginx user
#Requirements:
#	nginx must be running as nginx user
#	nginx must be listening on all active IPs on port 8080
#		You cannot use apt-get remove
#	Write a Bash script that configures the container to fit the above requirements
pkill apache
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart